### ISSUE TITLE
Infinite loader if I don't have any tasks assigned to me

### ISSUE THREAD

**Issue by brettimus** [codyogden/burrito#11]
Hey! I use trello mainly for personal organization. (I'm the only member of my boards)

I never assign stuff to myself, since that seems redundant. 

Anywho, I noticed that when I loaded the homepage, I got an infinite spinner. When I assigned something to myself on a board, the spinner went away.

You probably already know this is a thing! But I figured I'd let you know.

Oh and I also wanted to say that I found the site through the magic burrito that made it into the codepen newsletter (you're famous!), and also also I grew up in Minnesota, if that's relevant.

Also I like burritos.

**Comment by codyogden** [comment]
Thank you for the report!!! This is actually something I wasn’t aware of! I
don’t think I’ve had “Trello inbox zero” in over a year. :)

I’ll add a little info for when no cards are found. Thanks again!
